/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_device_model_string            16
#define gattdb_sn_string                      18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_software_revision_string       24
#define gattdb_sensor_batch_number_string     26
#define gattdb_continuous_glucose_monitoring_0 27
#define gattdb_cgm_measurement                29
#define gattdb_cgm_feature                    32
#define gattdb_cgm_status                     34
#define gattdb_record_access_control_point    36
#define gattdb_cgm_session_start_time         39
#define gattdb_cgm_session_run_time           41
#define gattdb_cgm_specific_ops_control_point 43
#define gattdb_battery_service                45
#define gattdb_batt_measurement               47
#define gattdb_power_source                   49
#define gattdb_power_source_type              51
#define gattdb_ota                            52
#define gattdb_ota_control                    54


#endif // __GATT_DB_H
