/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_software_revision_string       24
#define gattdb_continuous_glucose_monitoring_0 25
#define gattdb_cgm_measurement                27
#define gattdb_cgm_feature                    30
#define gattdb_cgm_status                     32
#define gattdb_cgm_session_start_time         35
#define gattdb_record_access_control_point    37
#define gattdb_cgm_specific_ops_control_point 40
#define gattdb_battery_service_0              42
#define gattdb_battery_level                  44
#define gattdb_characteristic_presentation_format 45


#endif // __GATT_DB_H
